
import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import { headers } from "next/headers";
import AppSideBar from "@/components/layouts/AppSideBar";
import toast, { Toaster } from 'react-hot-toast';
import { Page } from "@/models/Page";
import mongoose from "mongoose";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLink } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";
//const inter = Inter({ subsets: ["latin"] });

const lato = Lato({ subsets: ["latin"], weight: ['400', '700'] });


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function AppLayout({ children, ...rest }) {

    const headerList = headers();
    /*
        const url = headerList.get('next-url');
        console.log('nextuRllllll', headerList.get('next-url'));
        console.log([...headerList])

    */

    const session = await getServerSession(authOptions)
    if (!session) {
        return redirect('/');
    }

    mongoose.connect(process.env.MONGODB_URI);

    const page = await Page.findOne({
        owner: session.user.email
    });

    return (
        <html lang="en">
            <body className={lato.className}>
                <main className="flex min-h-screen">
                    <Toaster />
                    <aside className="bg-white w-48 p-4 pt-8 shadow">
                        <div className="sticky top-0">
                            <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
                                <Image src={session.user.image} width={256} height={256} alt={'avatar'} />
                            </div>
                            {page && (
                                <Link href={'/' + page.uri} target="blank" className="text-center mt-4 flex gap-2 items-center justify-center">
                                    <FontAwesomeIcon icon={faLink} size="lg" className="text-blue-500" />
                                    <span className="text-xl text-grap-300">/</span>
                                    <span>{page.uri}</span>
                                </Link>
                            )}

                            <div className="text-center">
                                <AppSideBar />
                            </div>
                        </div>
                    </aside>

                    <div className="grow">
                        {children}
                    </div>
                </main>
            </body>
        </html>
    );
}
